In [1]:
import pandas as pd

In [2]:
from datasets import load_dataset
import matplotlib.pyplot as plt

c:\Users\aarni\anaconda3\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
#loading data
dataset = load_dataset ('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

In [4]:
# data cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [5]:
df.iloc[0]

job_title_short                                       Senior Data Engineer
job_title                Senior Clinical Data Engineer / Principal Clin...
job_location                                                 Watertown, CT
job_via                                                    via Work Nearby
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                       Texas, United States
job_posted_date                                        2023-06-16 13:44:15
job_no_degree_mention                                                False
job_health_insurance                                                 False
job_country                                                  United States
salary_rate                                                           None
salary_year_avg                                                        NaN
salary_hour_avg                                                        NaN
company_name                                          Boehringer Ingelheim
job_skills                                                            None
job_type_skills                                                       None
Name: 0, dtype: object

In [6]:
# .loc with subsetting nan values (cleaning data)
df.loc[:, "salary_rate": "salary_hour_avg"].dropna(subset='salary_rate')

       salary_rate  salary_year_avg  salary_hour_avg
28            year         109500.0              NaN
43            hour              NaN             97.5
51            hour              NaN             72.5
77            year         140000.0              NaN
92            year         120000.0              NaN
...            ...              ...              ...
785624        year         139216.0              NaN
785641        year         150000.0              NaN
785648        year         221875.0              NaN
785682        year         157500.0              NaN
785692        year         157500.0              NaN

[33067 rows x 3 columns]

In [7]:
df.pivot_table(values='salary_hour_avg', index='job_country', columns='job_title_short', aggfunc='median')

job_title_short,Business Analyst,Cloud Engineer,Data Analyst,Data Engineer,Data Scientist,Machine Learning Engineer,Senior Data Analyst,Senior Data Engineer,Senior Data Scientist,Software Engineer
job_country,,,,,,,,,,
Algeria,NaN,NaN,15.000000,25.000,NaN,NaN,NaN,NaN,NaN,NaN
Argentina,NaN,NaN,NaN,80.000,NaN,NaN,NaN,NaN,NaN,NaN
Australia,20.000000,20.000000,20.000000,20.000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
Austria,NaN,NaN,15.000000,25.000,NaN,NaN,NaN,NaN,NaN,NaN
Bahamas,NaN,NaN,15.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Belarus,NaN,NaN,NaN,NaN,13.000000,NaN,NaN,NaN,NaN,NaN
Belgium,NaN,NaN,NaN,NaN,25.000000,NaN,NaN,NaN,NaN,NaN
Benin,NaN,NaN,15.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bolivia,NaN,NaN,NaN,80.000,NaN,NaN,NaN,NaN,NaN,NaN
Brazil,NaN,NaN,NaN,65.625,27.500000,NaN,NaN,NaN,NaN,NaN
Cameroon,NaN,NaN,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Canada,33.000000,42.500000,25.500000,55.000,25.500000,87.500000,NaN,61.500000,NaN,45.500000
Chile,NaN,NaN,15.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Colombia,NaN,NaN,NaN,80.000,15.000000,NaN,30.000000,NaN,NaN,NaN
Costa Rica,NaN,NaN,13.500000,NaN,NaN,NaN,NaN,52.500000,NaN,NaN
France,NaN,NaN,25.000000,NaN,25.000000,NaN,NaN,NaN,25.000000,NaN
Gambia,NaN,NaN,15.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Germany,25.000000,NaN,25.000000,NaN,25.000000,NaN,NaN,NaN,NaN,NaN
Ghana,NaN,NaN,NaN,25.000,25.000000,NaN,NaN,NaN,NaN,NaN
Guam,NaN,NaN,10.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hungary,NaN,NaN,NaN,26.000,NaN,NaN,NaN,NaN,NaN,NaN
India,25.000000,NaN,25.000000,25.000,25.000000,NaN,NaN,NaN,NaN,NaN
Indonesia,20.000000,NaN,20.000000,20.000,20.000000,NaN,NaN,NaN,NaN,NaN
Jamaica,NaN,NaN,NaN,80.000,NaN,NaN,NaN,NaN,NaN,NaN
Japan,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mexico,NaN,NaN,15.000000,80.000,NaN,NaN,NaN,NaN,NaN,50.000000
Netherlands,NaN,NaN,25.000000,NaN,25.000000,NaN,NaN,NaN,NaN,NaN
New Zealand,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Nigeria,NaN,NaN,NaN,15.000,NaN,NaN,NaN,NaN,NaN,NaN
Pakistan,15.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.000000
Paraguay,NaN,NaN,NaN,80.000,NaN,NaN,NaN,NaN,NaN,NaN
Peru,NaN,NaN,12.000000,80.000,NaN,NaN,NaN,NaN,NaN,NaN
Philippines,NaN,NaN,25.000000,NaN,25.000000,NaN,NaN,NaN,NaN,50.000000
Portugal,NaN,NaN,NaN,NaN,25.000000,NaN,NaN,NaN,NaN,NaN
Puerto Rico,12.750000,NaN,13.049999,52.500,NaN,NaN,NaN,NaN,NaN,30.000000
Singapore,NaN,NaN,25.000000,31.000,25.000000,NaN,NaN,NaN,NaN,NaN
South Korea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.000000
Spain,NaN,NaN,20.000000,NaN,25.000000,NaN,NaN,NaN,NaN,50.000000
Sudan,33.190002,44.200001,35.000000,57.500,42.855000,60.000000,24.000000,61.159996,52.500000,51.855000
Taiwan,NaN,NaN,8.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Thailand,NaN,NaN,NaN,NaN,NaN,19.000000,NaN,NaN,NaN,NaN
Turkey,NaN,NaN,NaN,NaN,15.500000,NaN,NaN,NaN,NaN,51.250000
U.S. Virgin Islands,NaN,NaN,16.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United Arab Emirates,NaN,NaN,25.000000,NaN,NaN,NaN,25.000000,NaN,NaN,NaN
United Kingdom,NaN,NaN,40.000000,54.500,NaN,NaN,NaN,42.500000,NaN,NaN
United States,41.750000,40.790001,33.000000,60.000,47.620003,41.924999,47.620003,62.500000,47.620003,49.974998
Venezuela,NaN,NaN,NaN,80.000,NaN,NaN,NaN,NaN,NaN,NaN
Zimbabwe,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.pivot_table(values='job_title_short', index='job_country', columns='job_title_short', aggfunc='count')

ValueError: Grouper for 'job_title_short' not 1-dimensional