In [1]:
import pandas as pd

In [2]:
from datasets import load_dataset
import matplotlib.pyplot as plt

c:\Users\aarni\anaconda3\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
dataset = load_dataset ('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [4]:
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [5]:
median_salary_year = df['salary_year_avg'].median()

In [6]:
median_salary_hour = df['salary_hour_avg'].median()

In [7]:
df_filled = df
df_filled['salary_year_avg'] = df_filled['salary_year_avg'].fillna(median_salary_year)
df_filled['salary_hour_avg'] = df_filled['salary_hour_avg'].fillna(median_salary_hour)

In [8]:
# dataframed with NaN values filled with median values
df_filled.loc[0:10]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,115000.0,45.98,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,115000.0,45.98,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,115000.0,45.98,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,115000.0,45.98,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,115000.0,45.98,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,115000.0,45.98,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,None,115000.0,45.98,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
7,Data Engineer,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49,False,False,Romania,None,115000.0,45.98,Zitec,"['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu...","{'cloud': ['gcp', 'azure', 'aws', 'bigquery', ..."
8,Business Analyst,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34,False,False,Denmark,None,115000.0,45.98,Hempel,"['excel', 'powerpoint', 'power bi']","{'analyst_tools': ['excel', 'powerpoint', 'pow..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,None,115000.0,45.98,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
10,Data Engineer,Erfahrene*r Data Engineer*in (m/w/d),"Basel, Switzerland",via LinkedIn,Full-time,False,Switzerland,2023-04-17 13:27:32,True,False,Switzerland,None,115000.0,45.98,ROCKEN®,"['python', 'databricks', 'azure', 'spark']","{'cloud': ['databricks', 'azure'], 'libraries'..."

In [9]:
df_unique = df_filled
df_unique = df_unique.drop_duplicates()

In [10]:
# dropping same job titles from a same company
df_unique = df_unique.drop_duplicates(subset=['job_title', 'company_name'])

In [11]:
df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
244570,Business Analyst,Summer Business Analyst Intern,"Queluz, Portugal",via BeBee Portugal,Internship,False,Portugal,2023-08-30 07:28:43,False,False,Portugal,None,115000.0,45.98,"Mckinsey & Company, Inc.",None,None
257375,Data Scientist,"Data Scientist, gt.school (Remote) - $60,000/y...",Anywhere,via LinkedIn,Full-time and Contractor,True,Singapore,2023-12-15 07:42:45,False,False,Singapore,None,115000.0,45.98,Crossover,"['python', 'r', 'javascript']","{'programming': ['python', 'r', 'javascript']}"
382256,Data Scientist,Data Scientist,Australia,via Jooble,Full-time,False,Australia,2023-11-02 18:15:41,False,False,Australia,None,115000.0,45.98,Engie Rinnovabili S.P.A.,"['python', 'c#', 'flow']","{'other': ['flow'], 'programming': ['python', ..."
407444,Data Analyst,Data Analyst – 637 Capital,Kenya,via BeBee Kenya,Full-time,False,Kenya,2023-04-22 16:19:47,True,False,Kenya,None,115000.0,45.98,Staffrite,"['c', 'python', 'postgresql', 'numpy', 'pandas...","{'analyst_tools': ['power bi'], 'databases': [..."
523134,Data Scientist,DATA SCIENTIST / ENGINEER SKYWISE (H/F),"Toulouse, France",via Indeed,Full-time,False,France,2023-01-23 11:12:03,False,False,France,None,115000.0,45.98,Airbus Protect SAS,"['sas', 'sas', 'nosql', 'neo4j', 'aws']","{'analyst_tools': ['sas'], 'cloud': ['aws'], '..."
50378,Software Engineer,"Devops Engineer, 100% En remoto",Spain,via BeBee,Full-time,False,Spain,2023-11-28 06:27:02,True,False,Spain,None,115000.0,45.98,Grupo CMC,"['python', 'oracle', 'ansible', 'jenkins', 'gi...","{'cloud': ['oracle'], 'other': ['ansible', 'je..."
698868,Senior Data Engineer,Senior Data Engineer,Anywhere,via LinkedIn,Full-time,True,"California, United States",2023-08-20 03:06:13,False,True,United States,None,115000.0,45.98,Motion Recruitment,"['sql', 'python', 'r', 'azure', 'aws', 'spark']","{'cloud': ['azure', 'aws'], 'libraries': ['spa..."
558185,Senior Data Scientist,Senior Manager of Data Intelligence,"Cloppenburg, Germany",via Melga,Full-time,False,Germany,2023-02-13 04:35:39,False,False,Germany,None,115000.0,45.98,ADAMA Deutschland,"['python', 'sql']","{'programming': ['python', 'sql']}"
241978,Data Engineer,Data Engineer,"Malmesbury, United Kingdom",via Dyson Careers,Full-time,False,United Kingdom,2023-04-06 07:21:43,False,False,United Kingdom,None,115000.0,45.98,Dyson,"['python', 'sql', 'gcp', 'bigquery', 'airflow'...","{'cloud': ['gcp', 'bigquery'], 'libraries': ['..."
234750,Data Scientist,Data Scientist – Finance,"Enkhuizen, Netherlands",via Ai-Jobs.net,Full-time,False,Netherlands,2023-01-10 07:42:49,False,False,Netherlands,year,157500.0,45.98,Syngenta Group,"['python', 'sql', 'aws', 'numpy', 'pandas', 's...","{'analyst_tools': ['power bi', 'tableau'], 'cl..."

In [12]:
df.sample(10, random_state=42)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
502901,Senior Data Engineer,Senior Data Engineer,"St Paul, MN",via BeBee,Full-time,False,"Florida, United States",2023-12-17 11:09:06,False,False,United States,None,115000.0,45.98,ManpowerGroup,"['sql', 'azure', 'git']","{'cloud': ['azure'], 'other': ['git'], 'progra..."
406337,Senior Data Scientist,Senior Analytics Engineer,"London, UK",via LinkedIn,Full-time,False,United Kingdom,2023-10-06 16:09:56,False,False,United Kingdom,None,115000.0,45.98,Harnham,"['sql', 'python', 'bigquery', 'snowflake', 'lo...","{'analyst_tools': ['looker'], 'cloud': ['bigqu..."
659951,Data Engineer,Data Engineer,"Newcastle upon Tyne, UK",via Indeed,Full-time,False,United Kingdom,2023-09-06 10:11:25,True,False,United Kingdom,None,115000.0,45.98,Morgan King,None,None
541593,Data Analyst,Data Analyst,Malta,via Trabajo.org,Full-time,False,Malta,2023-02-14 21:14:18,True,False,Malta,None,115000.0,45.98,Konnekt,['jira'],{'async': ['jira']}
425158,Senior Data Engineer,Senior Data Engineer. Job in Amsterdam NBC4i Jobs,"Amsterdam, Netherlands",via NBC4i Jobs,Full-time,False,Netherlands,2023-06-19 16:34:30,True,False,Netherlands,None,115000.0,45.98,Independent Recruiters,['python'],{'programming': ['python']}
183426,Data Analyst,Data Analyst,Singapore,via Singapore | JobsDB,Full-time,False,Singapore,2023-11-09 16:07:57,False,False,Singapore,None,115000.0,45.98,FLEXOSENSE PTE. LTD.,"['r', 'python', 'java', 'sql', 'sql server', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
287790,Data Analyst,Data Analyst,"Tampa, FL",via LinkedIn,Full-time,False,"Florida, United States",2023-07-14 17:02:23,True,False,United States,None,115000.0,45.98,Iris Software Inc.,"['sql', 'hadoop', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['ha..."
541983,Data Analyst,"Data Analyst, Cloud Systems Jobs","Chantilly, VA",via Clearance Jobs,Full-time,False,Georgia,2023-06-15 19:44:34,False,False,United States,None,115000.0,45.98,SAIC,"['sql', 'r', 'matlab', 'python', 'oracle', 'aw...","{'analyst_tools': ['power bi', 'tableau', 'qli..."
416896,Data Scientist,Alternant Actuariat & Data Science H/F,France,via LinkedIn,Full-time,False,France,2023-09-22 16:47:24,False,False,France,None,115000.0,45.98,KPMG France,None,None
780907,Data Engineer,"Data Engineer with Fivetran,Qlik Must","Mexico City, CDMX, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-16 06:19:09,False,False,Mexico,None,115000.0,45.98,CORUS Consulting,"['oracle', 'snowflake', 'aws', 'azure', 'alter...","{'analyst_tools': ['alteryx'], 'cloud': ['orac..."

In [13]:
df.pivot_table(values='salary_hour_avg', index='job_country', columns='job_title_short', aggfunc='median')

job_title_short,Business Analyst,Cloud Engineer,Data Analyst,Data Engineer,Data Scientist,Machine Learning Engineer,Senior Data Analyst,Senior Data Engineer,Senior Data Scientist,Software Engineer
job_country,,,,,,,,,,
Afghanistan,45.98,NaN,45.98,NaN,45.98,NaN,45.98,NaN,NaN,NaN
Albania,45.98,45.98,45.98,45.98,45.98,45.98,45.98,45.98,45.98,45.98
Algeria,45.98,45.98,45.98,45.98,45.98,45.98,NaN,45.98,NaN,45.98
Angola,45.98,NaN,45.98,45.98,45.98,NaN,NaN,NaN,45.98,45.98
Argentina,45.98,45.98,45.98,45.98,45.98,45.98,45.98,45.98,45.98,45.98
...,...,...,...,...,...,...,...,...,...,...
Venezuela,45.98,45.98,45.98,45.98,45.98,45.98,45.98,45.98,45.98,45.98
Vietnam,45.98,45.98,45.98,45.98,45.98,45.98,45.98,45.98,45.98,45.98
Yemen,45.98,NaN,45.98,45.98,NaN,NaN,NaN,NaN,NaN,45.98
Zambia,45.98,45.98,45.98,45.98,45.98,45.98,45.98,NaN,45.98,45.98
Zimbabwe,45.98,45.98,45.98,45.98,45.98,45.98,45.98,45.98,45.98,45.98

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        785741 non-null  float64
 13  salary_hour_avg        785741 non-null  float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

NameError: name 'df_q1' is not defined